name: Cloud
on: [pull_request]

jobs:
  aws_cdk:
    runs-on: ubuntu-latest
    steps:
      ## TODO: until docker fix
      - name: golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.14
        id: go

      ##
      ##
      - name: fix GOPATH
        run: |
          echo "##[set-env name=GOPATH;]$GITHUB_WORKSPACE"
          echo "##[add-path]$GITHUB_WORKSPACE/bin"
        shell: bash

      ##
      ##
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: src/github.com/${{ github.repository }}

      ##
      ## TODO: until docker fix
      - name: go get deps
        run: |
          go get -v -t -d github.com/${{ github.repository }}/...
          

      - name: install
        run: |
          npm -C src/github.com/${{ github.repository }}/cloud install 

      - name: synth
        run: |
          npm -C src/github.com/${{ github.repository }}/cloud run synth