name: Cloud
on: [pull_request]

jobs:
  aws_cdk:
    runs-on: ubuntu-latest
    if:  github.actor == 'facebadge'
    steps:
      - name: golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.14
        id: go

      - name: fix GOPATH
        run: |
          echo "##[set-env name=GOPATH;]$GITHUB_WORKSPACE"
          echo "##[add-path]$GITHUB_WORKSPACE/bin"
        shell: bash

      - name: checkout
        uses: actions/checkout@v2
        with:
          path: src/github.com/${{ github.repository }}

      - name: go get deps
        run: |
          go get -v -t -d github.com/${{ github.repository }}/...
          
      - name: install
        run: |
          npm -C src/github.com/${{ github.repository }}/cloud \
            install 

      - name: tsc
        run: |
          npm -C src/github.com/${{ github.repository }}/cloud \
            run tsc
  
      - name: aws access
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: eu-west-1
  
      # - name: deploy
      #   run: |
      #     npm -C src/github.com/${{ github.repository }}/cloud \
      #       run -- cdk deploy example-pr${{ github.event.number }} \
      #       -c vsn=pr${{ github.event.number }} \
      #       -c domain=${{ secrets.CONFIG_DOMAIN }}

      - name: assay
        run: |
          go get github.com/assay-it/assay
          assay \
            -api latest.assay.it \
            -secret ${{ secrets.ASSAY_SECRET_KEY }} \
            -source ${{ github.repository }} \
            -branch ${{ github.ref }} \
            -commit ${{ github.sha }} \
            -number ${{ github.event.number }} \
            -title ${{ github.event.pull_request.title }}

        