name: Cloud
on: [pull_request]

jobs:
  aws_cdk:
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v2

      - name: cdk synth
        uses: youyo/aws-cdk-github-actions@v1
        with:
          cdk_subcommand: 'synth'
          cdk_version: '1.47.0'
          working_dir: './cloud'
