name: Cloud
on: [pull_request]

jobs:
  aws_cdk:
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v2

      - name: install
        run: |
          npm install -g ts-node aws-cdk
          npm -C cloud install 

      - name: synth
        run: npm -C cloud run synth